SFTP:
  IP: "172.16.1.39"
  PORT: 22
  USERNAME: "root"
  PASSWORD: "i1root"

API:
  WEATHER_API_KEY: "e1f10a1e78da46f5b10a1e78da96f525"
  UNITS: "m"

SYSTEM:
  DATA_MINUTE_INTERVAL: 30
  NTP_MINUTE_INTERVAL: 60
  RADAR_MINUTE_INTERVAL: 10
  NTP_SERVERS:
    - "time.nist.gov"
    - "pool.ntp.org"
    - "time.google.com"
  
  COLOREDLOGS:
    level: 'INFO'
    fmt: '%(asctime)s %(levelname)s %(message)s'
    field_styles:
      asctime:
        color: 'cyan'
      levelname:
        color: 'magenta'
        style: 'bright'