SFTP:
  IP: "172.16.1.39"
  PORT: 22
  USERNAME: "root"
  PASSWORD: "i1root"

API:
  WEATHER_API_KEY: "e1f10a1e78da46f5b10a1e78da96f525"
  UNITS: "e"

SYSTEM:
  DATA_MINUTE_INTERVAL: 30
  NTP_MINUTE_INTERVAL: 60
  NTP1: "time.nist.gov"
  NTP2: "pool.ntp.org"
